/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class Connectable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Connectable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Connectable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_Connectable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    umundoNativeJavaJNI.Connectable_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    umundoNativeJavaJNI.Connectable_change_ownership(this, swigCPtr, true);
  }

  public PublisherMap getPublishers() {
    return new PublisherMap((getClass() == Connectable.class) ? umundoNativeJavaJNI.Connectable_getPublishers(swigCPtr, this) : umundoNativeJavaJNI.Connectable_getPublishersSwigExplicitConnectable(swigCPtr, this), true);
  }

  public SubscriberMap getSubscribers() {
    return new SubscriberMap((getClass() == Connectable.class) ? umundoNativeJavaJNI.Connectable_getSubscribers(swigCPtr, this) : umundoNativeJavaJNI.Connectable_getSubscribersSwigExplicitConnectable(swigCPtr, this), true);
  }

  public void addedToNode(Node node) {
    if (getClass() == Connectable.class) umundoNativeJavaJNI.Connectable_addedToNode(swigCPtr, this, Node.getCPtr(node), node); else umundoNativeJavaJNI.Connectable_addedToNodeSwigExplicitConnectable(swigCPtr, this, Node.getCPtr(node), node);
  }

  public void removedFromNode(Node node) {
    if (getClass() == Connectable.class) umundoNativeJavaJNI.Connectable_removedFromNode(swigCPtr, this, Node.getCPtr(node), node); else umundoNativeJavaJNI.Connectable_removedFromNodeSwigExplicitConnectable(swigCPtr, this, Node.getCPtr(node), node);
  }

  public Connectable() {
    this(umundoNativeJavaJNI.new_Connectable(), true);
    umundoNativeJavaJNI.Connectable_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
