/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class EndPointConfig extends Options {
  private long swigCPtr;

  protected EndPointConfig(long cPtr, boolean cMemoryOwn) {
    super(umundoNativeJavaJNI.EndPointConfig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EndPointConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_EndPointConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EndPointConfig(int port) {
    this(umundoNativeJavaJNI.new_EndPointConfig__SWIG_0(port), true);
  }

  public EndPointConfig() {
    this(umundoNativeJavaJNI.new_EndPointConfig__SWIG_1(), true);
  }

  public EndPointConfig(String address) {
    this(umundoNativeJavaJNI.new_EndPointConfig__SWIG_2(address), true);
  }

  public String getType() {
    return umundoNativeJavaJNI.EndPointConfig_getType(swigCPtr, this);
  }

  public void setPort(int nodePort) {
    umundoNativeJavaJNI.EndPointConfig_setPort(swigCPtr, this, nodePort);
  }

  public void setIP(String nodeIp) {
    umundoNativeJavaJNI.EndPointConfig_setIP(swigCPtr, this, nodeIp);
  }

  public final static class Protocol {
    public final static EndPointConfig.Protocol TCP = new EndPointConfig.Protocol("TCP");
    public final static EndPointConfig.Protocol UDP = new EndPointConfig.Protocol("UDP");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Protocol swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Protocol.class + " with value " + swigValue);
    }

    private Protocol(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Protocol(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Protocol(String swigName, Protocol swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Protocol[] swigValues = { TCP, UDP };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
