/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class Greeter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Greeter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Greeter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_Greeter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    umundoNativeJavaJNI.Greeter_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    umundoNativeJavaJNI.Greeter_change_ownership(this, swigCPtr, true);
  }

  public void welcome(Publisher arg0, SubscriberStub arg1) {
    umundoNativeJavaJNI.Greeter_welcome(swigCPtr, this, Publisher.getCPtr(arg0), arg0, SubscriberStub.getCPtr(arg1), arg1);
  }

  public void farewell(Publisher arg0, SubscriberStub arg1) {
    umundoNativeJavaJNI.Greeter_farewell(swigCPtr, this, Publisher.getCPtr(arg0), arg0, SubscriberStub.getCPtr(arg1), arg1);
  }

  public Greeter() {
    this(umundoNativeJavaJNI.new_Greeter(), true);
    umundoNativeJavaJNI.Greeter_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
