/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class Host {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Host(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Host obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_Host(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String getHostname() {
    return umundoNativeJavaJNI.Host_getHostname();
  }

  public static InterfaceArray getInterfaces() {
    return new InterfaceArray(umundoNativeJavaJNI.Host_getInterfaces(), true);
  }

  public static String getHostId() {
    return umundoNativeJavaJNI.Host_getHostId();
  }

  public Host() {
    this(umundoNativeJavaJNI.new_Host(), true);
  }

}
