/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class InterfaceArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected InterfaceArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InterfaceArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_InterfaceArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InterfaceArray() {
    this(umundoNativeJavaJNI.new_InterfaceArray__SWIG_0(), true);
  }

  public InterfaceArray(long n) {
    this(umundoNativeJavaJNI.new_InterfaceArray__SWIG_1(n), true);
  }

  public long size() {
    return umundoNativeJavaJNI.InterfaceArray_size(swigCPtr, this);
  }

  public long capacity() {
    return umundoNativeJavaJNI.InterfaceArray_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    umundoNativeJavaJNI.InterfaceArray_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return umundoNativeJavaJNI.InterfaceArray_isEmpty(swigCPtr, this);
  }

  public void clear() {
    umundoNativeJavaJNI.InterfaceArray_clear(swigCPtr, this);
  }

  public void add(Interface x) {
    umundoNativeJavaJNI.InterfaceArray_add(swigCPtr, this, Interface.getCPtr(x), x);
  }

  public Interface get(int i) {
    return new Interface(umundoNativeJavaJNI.InterfaceArray_get(swigCPtr, this, i), false);
  }

  public void set(int i, Interface val) {
    umundoNativeJavaJNI.InterfaceArray_set(swigCPtr, this, i, Interface.getCPtr(val), val);
  }

}
