/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class Interface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Interface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Interface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_Interface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIpv4(StringArray value) {
    umundoNativeJavaJNI.Interface_ipv4_set(swigCPtr, this, StringArray.getCPtr(value), value);
  }

  public StringArray getIpv4() {
    long cPtr = umundoNativeJavaJNI.Interface_ipv4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringArray(cPtr, false);
  }

  public void setIpv6(StringArray value) {
    umundoNativeJavaJNI.Interface_ipv6_set(swigCPtr, this, StringArray.getCPtr(value), value);
  }

  public StringArray getIpv6() {
    long cPtr = umundoNativeJavaJNI.Interface_ipv6_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringArray(cPtr, false);
  }

  public void setMac(String value) {
    umundoNativeJavaJNI.Interface_mac_set(swigCPtr, this, value);
  }

  public String getMac() {
    return umundoNativeJavaJNI.Interface_mac_get(swigCPtr, this);
  }

  public void setName(String value) {
    umundoNativeJavaJNI.Interface_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return umundoNativeJavaJNI.Interface_name_get(swigCPtr, this);
  }

  public Interface() {
    this(umundoNativeJavaJNI.new_Interface(), true);
  }

}
