/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class NodeStubMap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NodeStubMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeStubMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_NodeStubMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NodeStubMap() {
    this(umundoNativeJavaJNI.new_NodeStubMap__SWIG_0(), true);
  }

  public NodeStubMap(NodeStubMap arg0) {
    this(umundoNativeJavaJNI.new_NodeStubMap__SWIG_1(NodeStubMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return umundoNativeJavaJNI.NodeStubMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return umundoNativeJavaJNI.NodeStubMap_empty(swigCPtr, this);
  }

  public void clear() {
    umundoNativeJavaJNI.NodeStubMap_clear(swigCPtr, this);
  }

  public NodeStub get(String key) {
    return new NodeStub(umundoNativeJavaJNI.NodeStubMap_get(swigCPtr, this, key), false);
  }

  public void set(String key, NodeStub x) {
    umundoNativeJavaJNI.NodeStubMap_set(swigCPtr, this, key, NodeStub.getCPtr(x), x);
  }

  public void del(String key) {
    umundoNativeJavaJNI.NodeStubMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return umundoNativeJavaJNI.NodeStubMap_has_key(swigCPtr, this, key);
  }

}
