/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class NodeConfig extends EndPointConfig {
  private long swigCPtr;

  protected NodeConfig(long cPtr, boolean cMemoryOwn) {
    super(umundoNativeJavaJNI.NodeConfig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_NodeConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NodeConfig(int nodePort, int pubPort) {
    this(umundoNativeJavaJNI.new_NodeConfig__SWIG_0(nodePort, pubPort), true);
  }

  public NodeConfig() {
    this(umundoNativeJavaJNI.new_NodeConfig__SWIG_1(), true);
  }

  public NodeConfig(String address) {
    this(umundoNativeJavaJNI.new_NodeConfig__SWIG_2(address), true);
  }

  public String getType() {
    return umundoNativeJavaJNI.NodeConfig_getType(swigCPtr, this);
  }

  public void setPubPort(int pubPort) {
    umundoNativeJavaJNI.NodeConfig_setPubPort(swigCPtr, this, pubPort);
  }

  public void allowLocalConnections(boolean allow) {
    umundoNativeJavaJNI.NodeConfig_allowLocalConnections(swigCPtr, this, allow);
  }

}
