/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class Options {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_Options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getType() {
    return umundoNativeJavaJNI.Options_getType(swigCPtr, this);
  }

  public Options() {
    this(umundoNativeJavaJNI.new_Options(), true);
  }

}
