/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class PublisherStub extends EndPoint {
  private long swigCPtr;

  protected PublisherStub(long cPtr, boolean cMemoryOwn) {
    super(umundoNativeJavaJNI.PublisherStub_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublisherStub obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_PublisherStub(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PublisherStub() {
    this(umundoNativeJavaJNI.new_PublisherStub(), true);
  }

  public boolean isValid() {
    return umundoNativeJavaJNI.PublisherStub_isValid(swigCPtr, this);
  }

  public boolean equals(PublisherStub other) {
    return umundoNativeJavaJNI.PublisherStub_equals(swigCPtr, this, PublisherStub.getCPtr(other), other);
  }

  public String getChannelName() {
    return umundoNativeJavaJNI.PublisherStub_getChannelName(swigCPtr, this);
  }

  public boolean isRTP() {
    return umundoNativeJavaJNI.PublisherStub_isRTP(swigCPtr, this);
  }

  public final static class PublisherType {
    public final static PublisherStub.PublisherType ZEROMQ = new PublisherStub.PublisherType("ZEROMQ", 0x0001);
    public final static PublisherStub.PublisherType RTP = new PublisherStub.PublisherType("RTP", 0x0002);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static PublisherType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + PublisherType.class + " with value " + swigValue);
    }

    private PublisherType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private PublisherType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private PublisherType(String swigName, PublisherType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static PublisherType[] swigValues = { ZEROMQ, RTP };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
