/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class PublisherConfigMCast extends PublisherConfigRTP {
  private long swigCPtr;

  protected PublisherConfigMCast(long cPtr, boolean cMemoryOwn) {
    super(umundoNativeJavaJNI.PublisherConfigMCast_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublisherConfigMCast obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_PublisherConfigMCast(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PublisherConfigMCast(String channel) {
    this(umundoNativeJavaJNI.new_PublisherConfigMCast(channel), true);
  }

}
