/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class PublisherConfigTCP extends PublisherConfig {
  private long swigCPtr;

  protected PublisherConfigTCP(long cPtr, boolean cMemoryOwn) {
    super(umundoNativeJavaJNI.PublisherConfigTCP_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublisherConfigTCP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_PublisherConfigTCP(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PublisherConfigTCP(String channel) {
    this(umundoNativeJavaJNI.new_PublisherConfigTCP(channel), true);
  }

  public void enableCompression() {
    umundoNativeJavaJNI.PublisherConfigTCP_enableCompression(swigCPtr, this);
  }

}
