/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class PublisherStubMap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PublisherStubMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublisherStubMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_PublisherStubMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PublisherStubMap() {
    this(umundoNativeJavaJNI.new_PublisherStubMap__SWIG_0(), true);
  }

  public PublisherStubMap(PublisherStubMap arg0) {
    this(umundoNativeJavaJNI.new_PublisherStubMap__SWIG_1(PublisherStubMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return umundoNativeJavaJNI.PublisherStubMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return umundoNativeJavaJNI.PublisherStubMap_empty(swigCPtr, this);
  }

  public void clear() {
    umundoNativeJavaJNI.PublisherStubMap_clear(swigCPtr, this);
  }

  public PublisherStub get(String key) {
    return new PublisherStub(umundoNativeJavaJNI.PublisherStubMap_get(swigCPtr, this, key), false);
  }

  public void set(String key, PublisherStub x) {
    umundoNativeJavaJNI.PublisherStubMap_set(swigCPtr, this, key, PublisherStub.getCPtr(x), x);
  }

  public void del(String key) {
    umundoNativeJavaJNI.PublisherStubMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return umundoNativeJavaJNI.PublisherStubMap_has_key(swigCPtr, this, key);
  }

}
