/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class Receiver {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Receiver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Receiver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_Receiver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    umundoNativeJavaJNI.Receiver_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    umundoNativeJavaJNI.Receiver_change_ownership(this, swigCPtr, true);
  }

  public void receive(Message msg) {
    umundoNativeJavaJNI.Receiver_receive(swigCPtr, this, Message.getCPtr(msg), msg);
  }

  public Receiver() {
    this(umundoNativeJavaJNI.new_Receiver(), true);
    umundoNativeJavaJNI.Receiver_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
