/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class SubscriberConfigRTP extends SubscriberConfigTCP {
  private long swigCPtr;

  protected SubscriberConfigRTP(long cPtr, boolean cMemoryOwn) {
    super(umundoNativeJavaJNI.SubscriberConfigRTP_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriberConfigRTP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_SubscriberConfigRTP(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SubscriberConfigRTP(String channel) {
    this(umundoNativeJavaJNI.new_SubscriberConfigRTP(channel), true);
  }

  public void setPortbase(int port) {
    umundoNativeJavaJNI.SubscriberConfigRTP_setPortbase(swigCPtr, this, port);
  }

  public void setMulticastIP(String ip) {
    umundoNativeJavaJNI.SubscriberConfigRTP_setMulticastIP(swigCPtr, this, ip);
  }

  public void setMulticastPortbase(int port) {
    umundoNativeJavaJNI.SubscriberConfigRTP_setMulticastPortbase(swigCPtr, this, port);
  }

}
