/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class SubscriberMap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SubscriberMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriberMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_SubscriberMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SubscriberMap() {
    this(umundoNativeJavaJNI.new_SubscriberMap__SWIG_0(), true);
  }

  public SubscriberMap(SubscriberMap arg0) {
    this(umundoNativeJavaJNI.new_SubscriberMap__SWIG_1(SubscriberMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return umundoNativeJavaJNI.SubscriberMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return umundoNativeJavaJNI.SubscriberMap_empty(swigCPtr, this);
  }

  public void clear() {
    umundoNativeJavaJNI.SubscriberMap_clear(swigCPtr, this);
  }

  public Subscriber get(String key) {
    return new Subscriber(umundoNativeJavaJNI.SubscriberMap_get(swigCPtr, this, key), false);
  }

  public void set(String key, Subscriber x) {
    umundoNativeJavaJNI.SubscriberMap_set(swigCPtr, this, key, Subscriber.getCPtr(x), x);
  }

  public void del(String key) {
    umundoNativeJavaJNI.SubscriberMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return umundoNativeJavaJNI.SubscriberMap_has_key(swigCPtr, this, key);
  }

}
