/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

import java.util.HashMap;

public class Subscriber extends SubscriberStub {
  private long swigCPtr;

  protected Subscriber(long cPtr, boolean cMemoryOwn) {
    super(umundoNativeJavaJNI.Subscriber_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Subscriber obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_Subscriber(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  // keep receiver as a reference to prevent premature GC
  private Receiver _receiver;

  public void setReceiver(Receiver receiver) {
    // it is important to keep the reference, otherwise the Java GC will eat it!
    _receiver = receiver;
    setReceiverNative(receiver);
  }

	public HashMap<String, PublisherStub> getPublishers() {
		HashMap<String, PublisherStub> pubs = new HashMap<String, PublisherStub>();
		PublisherStubMap pubMap = getPublishersNative();
		StringArray pubKeys = getPubKeys();
		for (int i = 0; i < pubKeys.size(); i++) {
			pubs.put(pubKeys.get(i), pubMap.get(pubKeys.get(i)));
		}
		return pubs;
	}

  public Subscriber(String channelName) {
    this(umundoNativeJavaJNI.new_Subscriber__SWIG_0(channelName), true);
  }

  public Subscriber(SubscriberConfig config) {
    this(umundoNativeJavaJNI.new_Subscriber__SWIG_1(SubscriberConfig.getCPtr(config), config), true);
  }

  public Subscriber(SubscriberStub stub) {
    this(umundoNativeJavaJNI.new_Subscriber__SWIG_2(SubscriberStub.getCPtr(stub), stub), true);
  }

  public boolean isValid() {
    return umundoNativeJavaJNI.Subscriber_isValid(swigCPtr, this);
  }

  public boolean equals(Subscriber other) {
    return umundoNativeJavaJNI.Subscriber_equals(swigCPtr, this, Subscriber.getCPtr(other), other);
  }

  private void setReceiverNative(Receiver receiver) {
    umundoNativeJavaJNI.Subscriber_setReceiverNative(swigCPtr, this, Receiver.getCPtr(receiver), receiver);
  }

  public Receiver getReceiver() {
    long cPtr = umundoNativeJavaJNI.Subscriber_getReceiver(swigCPtr, this);
    return (cPtr == 0) ? null : new Receiver(cPtr, false);
  }

  public void setChannelName(String channelName) {
    umundoNativeJavaJNI.Subscriber_setChannelName(swigCPtr, this, channelName);
  }

  public Message getNextMsg() {
    long cPtr = umundoNativeJavaJNI.Subscriber_getNextMsg(swigCPtr, this);
    return (cPtr == 0) ? null : new Message(cPtr, false);
  }

  public boolean hasNextMsg() {
    return umundoNativeJavaJNI.Subscriber_hasNextMsg(swigCPtr, this);
  }

  private PublisherStubMap getPublishersNative() {
    return new PublisherStubMap(umundoNativeJavaJNI.Subscriber_getPublishersNative(swigCPtr, this), true);
  }

  public boolean isSubscribedTo(String uuid) {
    return umundoNativeJavaJNI.Subscriber_isSubscribedTo(swigCPtr, this, uuid);
  }

  public boolean matches(PublisherStub pub) {
    return umundoNativeJavaJNI.Subscriber_matches(swigCPtr, this, PublisherStub.getCPtr(pub), pub);
  }

  public void added(PublisherStub pub, NodeStub node) {
    umundoNativeJavaJNI.Subscriber_added(swigCPtr, this, PublisherStub.getCPtr(pub), pub, NodeStub.getCPtr(node), node);
  }

  public void removed(PublisherStub pub, NodeStub node) {
    umundoNativeJavaJNI.Subscriber_removed(swigCPtr, this, PublisherStub.getCPtr(pub), pub, NodeStub.getCPtr(node), node);
  }

  public void suspend() {
    umundoNativeJavaJNI.Subscriber_suspend(swigCPtr, this);
  }

  public void resume() {
    umundoNativeJavaJNI.Subscriber_resume(swigCPtr, this);
  }

  public StringArray getPubKeys() {
    return new StringArray(umundoNativeJavaJNI.Subscriber_getPubKeys(swigCPtr, this), true);
  }

}
