/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class SubscriberStubMap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SubscriberStubMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriberStubMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_SubscriberStubMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SubscriberStubMap() {
    this(umundoNativeJavaJNI.new_SubscriberStubMap__SWIG_0(), true);
  }

  public SubscriberStubMap(SubscriberStubMap arg0) {
    this(umundoNativeJavaJNI.new_SubscriberStubMap__SWIG_1(SubscriberStubMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return umundoNativeJavaJNI.SubscriberStubMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return umundoNativeJavaJNI.SubscriberStubMap_empty(swigCPtr, this);
  }

  public void clear() {
    umundoNativeJavaJNI.SubscriberStubMap_clear(swigCPtr, this);
  }

  public SubscriberStub get(String key) {
    return new SubscriberStub(umundoNativeJavaJNI.SubscriberStubMap_get(swigCPtr, this, key), false);
  }

  public void set(String key, SubscriberStub x) {
    umundoNativeJavaJNI.SubscriberStubMap_set(swigCPtr, this, key, SubscriberStub.getCPtr(x), x);
  }

  public void del(String key) {
    umundoNativeJavaJNI.SubscriberStubMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return umundoNativeJavaJNI.SubscriberStubMap_has_key(swigCPtr, this, key);
  }

}
