/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.umundo.core;

public class SubscriberConfigTCP extends SubscriberConfig {
  private long swigCPtr;

  protected SubscriberConfigTCP(long cPtr, boolean cMemoryOwn) {
    super(umundoNativeJavaJNI.SubscriberConfigTCP_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriberConfigTCP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        umundoNativeJavaJNI.delete_SubscriberConfigTCP(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SubscriberConfigTCP(String channel) {
    this(umundoNativeJavaJNI.new_SubscriberConfigTCP(channel), true);
  }

}
